<script setup lang="ts">
import {nextTick,ref,watch} from 'vue';
import {AlertTriangle,CheckCircle2,HelpCircle,X} from 'lucide-vue-next';
import {appDialog} from './appDialog';
const input=ref<HTMLInputElement>();
watch(()=>appDialog.state.visible,value=>{if(value&&appDialog.state.kind==='prompt')nextTick(()=>input.value?.focus())});
</script>

<template><Teleport to="body"><Transition name="dialog-fade"><div v-if="appDialog.state.visible" class="app-dialog-backdrop" @click.self="appDialog.finish(false)"><section class="app-dialog" role="dialog" aria-modal="true" :aria-label="appDialog.state.title"><button class="dialog-x" @click="appDialog.finish(false)"><X/></button><span class="dialog-icon" :class="{danger:appDialog.state.danger}"><AlertTriangle v-if="appDialog.state.danger"/><HelpCircle v-else-if="appDialog.state.kind!=='alert'"/><CheckCircle2 v-else/></span><h3>{{appDialog.state.title}}</h3><p>{{appDialog.state.message}}</p><input v-if="appDialog.state.kind==='prompt'" ref="input" v-model="appDialog.state.value" :type="appDialog.state.inputType" :placeholder="appDialog.state.placeholder" @keydown.enter="appDialog.state.value&&appDialog.finish(true)"><footer><button v-if="appDialog.state.kind!=='alert'" class="dialog-cancel" @click="appDialog.finish(false)">{{appDialog.state.cancelText}}</button><button class="dialog-confirm" :class="{danger:appDialog.state.danger}" :disabled="appDialog.state.kind==='prompt'&&!appDialog.state.value" @click="appDialog.finish(true)">{{appDialog.state.confirmText}}</button></footer></section></div></Transition></Teleport></template>

<style scoped>
.app-dialog-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:20px;background:#43394b4d;backdrop-filter:blur(5px)}.app-dialog{position:relative;width:min(420px,100%);padding:28px;border:1px solid #fff;border-radius:20px;background:#fff;box-shadow:0 28px 90px #2d203a35;text-align:center}.dialog-x{position:absolute;right:16px;top:16px;width:32px;height:32px;border:0;border-radius:9px;background:#f4f1f6;color:#817988;display:grid;place-items:center}.dialog-x svg{width:16px}.dialog-icon{width:48px;height:48px;margin:0 auto 14px;border-radius:15px;background:#eee9f8;color:#6c59b0;display:grid;place-items:center}.dialog-icon.danger{background:#fff0f2;color:#c84d62}.dialog-icon svg{width:22px}.app-dialog h3{margin:0;font-size:20px;color:#37313e}.app-dialog p{margin:9px auto 0;max-width:330px;color:#817a87;font-size:13px;line-height:1.65;white-space:pre-wrap}.app-dialog input{width:100%;margin-top:20px;padding:12px 13px;border:1px solid #ded8e5;border-radius:11px;outline:0}.app-dialog input:focus{border-color:#9d8dd4;box-shadow:0 0 0 4px #796bf50c}.app-dialog footer{display:flex;justify-content:flex-end;gap:9px;margin-top:24px}.app-dialog footer button{min-width:88px;border:0;border-radius:10px;padding:10px 15px;font-weight:600}.dialog-cancel{background:#f2eff5;color:#69616f}.dialog-confirm{background:#7562c8;color:#fff;box-shadow:0 7px 18px #6855bc2b}.dialog-confirm.danger{background:#c94c61;box-shadow:0 7px 18px #b13d5126}.dialog-confirm:disabled{opacity:.45;cursor:not-allowed}.dialog-fade-enter-active,.dialog-fade-leave-active{transition:.18s}.dialog-fade-enter-from,.dialog-fade-leave-to{opacity:0}.dialog-fade-enter-from .app-dialog,.dialog-fade-leave-to .app-dialog{transform:translateY(8px) scale(.98)}.app-dialog{transition:.18s}
</style>
