<script setup lang="ts">
import {ref} from 'vue';
import {useRouter} from 'vue-router';
import {api} from '../api';
import {ArrowRight,CheckCircle2} from 'lucide-vue-next';
const username=ref('admin'),password=ref('admin123'),loading=ref(false),error=ref(''),router=useRouter();
async function login(){loading.value=true;error.value='';try{const{data}=await api.post('/auth/login',{username:username.value,password:password.value});localStorage.setItem('token',data.token);localStorage.setItem('name',data.name);localStorage.setItem('role',data.role);if(data.avatarUrl)localStorage.setItem('avatarUrl',data.avatarUrl);else localStorage.removeItem('avatarUrl');router.push('/')}catch{error.value='用户名或密码错误，或账号已被禁用'}finally{loading.value=false}}
</script>
<template><main class="login"><section class="login-story"><div class="brand"><span class="brand-mark ggbond-logo"><img src="/ggbond-logo.jpg" alt="GGBOND logo"></span><span>GGBOND AI<small>KNOWLEDGE OS</small></span></div><div class="story-copy"><span class="eyebrow">SMART KNOWLEDGE, HAPPY WORK</span><h1>让组织的每一份知识，<br><em>聪明又好用。</em></h1><p>统一沉淀文档，让 GGBOND AI 基于可信内容，为团队提供准确、可追溯的答案。</p><ul><li><CheckCircle2/>私有知识安全管理</li><li><CheckCircle2/>答案来源清晰可追溯</li><li><CheckCircle2/>语义检索，轻松找答案</li></ul></div><div class="login-mascot"><img src="/ggbond-logo.jpg" alt="GGBOND AI mascot"></div><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div></section><section class="login-panel"><form @submit.prevent="login"><div class="mobile-brand">GGBOND AI</div><span class="eyebrow">欢迎回来</span><h2>登录知识中枢</h2><p class="muted">输入账号信息，和小猪助手一起探索知识。</p><label>账号<input v-model="username" autocomplete="username" placeholder="请输入账号"></label><label>密码<input v-model="password" type="password" autocomplete="current-password" placeholder="请输入密码"></label><p v-if="error" class="error">{{error}}</p><button class="primary login-btn" :disabled="loading">{{loading?'正在验证...':'进入工作台'}}<ArrowRight :size="18"/></button><p class="hint">演示账号：admin / admin123</p></form></section></main></template>
