<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {useRouter} from 'vue-router';
import {ArrowLeft,Check,KeyRound,Plus,Search,Shield,Trash2,UserCog,X} from 'lucide-vue-next';
import {api} from '../api';
import {appDialog} from '../components/appDialog';

type User={id:number,username:string,displayName:string,role:'ADMIN'|'USER',enabled:boolean};
const router=useRouter(),users=ref<User[]>([]),query=ref(''),showCreate=ref(false),busy=ref(false);
const form=ref({username:'',displayName:'',password:'',role:'USER'});
const filtered=computed(()=>users.value.filter(u=>(u.username+' '+u.displayName).toLowerCase().includes(query.value.toLowerCase())));
async function load(){users.value=(await api.get('/users')).data}
async function create(){busy.value=true;try{await api.post('/users',form.value);form.value={username:'',displayName:'',password:'',role:'USER'};showCreate.value=false;await load()}finally{busy.value=false}}
async function save(user:User){await api.patch(`/users/${user.id}`,{displayName:user.displayName,role:user.role,enabled:user.enabled});await load()}
async function toggle(user:User){user.enabled=!user.enabled;try{await save(user)}catch{user.enabled=!user.enabled}}
async function resetPassword(user:User){const password=await appDialog.prompt({title:'重置用户密码',message:`为 ${user.username} 设置新密码，密码至少需要 6 位。`,confirmText:'重置密码',inputType:'password',placeholder:'请输入新密码'});if(!password)return;if(password.length<6){await appDialog.alert({title:'密码不符合要求',message:'新密码至少需要 6 位。'});return}await api.put(`/users/${user.id}/password`,{password});await appDialog.alert({title:'重置成功',message:`用户 ${user.username} 的密码已经更新。`})}
async function remove(user:User){if(!await appDialog.confirm({title:'删除用户',message:`确认删除用户“${user.username}”吗？其普通空间成员关系也会被清理。`,confirmText:'删除用户',danger:true}))return;await api.delete(`/users/${user.id}`);await load()}
onMounted(load);
</script>

<template><main class="users-page"><header><button class="back" @click="router.push('/')"><ArrowLeft/>返回工作台</button><div><span class="eyebrow">ADMINISTRATION</span><h1>用户管理</h1><p>维护系统账号、角色和登录状态。</p></div><button class="primary" @click="showCreate=true"><Plus/>新增用户</button></header>
  <section class="users-card"><div class="users-toolbar"><div class="search-box"><Search/><input v-model="query" placeholder="搜索用户名或姓名"></div><span>共 {{users.length}} 个用户</span></div>
    <div class="user-table"><div class="table-head"><span>用户</span><span>系统角色</span><span>状态</span><span>操作</span></div>
      <article v-for="user in filtered" :key="user.id"><div class="user-name"><span>{{user.displayName?.slice(0,1)||user.username.slice(0,1)}}</span><label><input v-model="user.displayName" @change="save(user)"><small>@{{user.username}}</small></label></div><select v-model="user.role" @change="save(user)"><option value="ADMIN">管理员</option><option value="USER">普通用户</option></select><button class="status-switch" :class="{enabled:user.enabled}" @click="toggle(user)"><i></i>{{user.enabled?'已启用':'已禁用'}}</button><div class="row-actions"><button title="重置密码" @click="resetPassword(user)"><KeyRound/></button><button class="remove" title="删除用户" @click="remove(user)"><Trash2/></button></div></article>
      <div v-if="!filtered.length" class="no-users"><UserCog/>没有匹配的用户</div>
    </div>
  </section>
  <div v-if="showCreate" class="modal-backdrop" @click.self="showCreate=false"><form class="modal" @submit.prevent="create"><button type="button" class="modal-close" @click="showCreate=false"><X/></button><span class="eyebrow">NEW USER</span><h2>新增用户</h2><label>用户名<input v-model="form.username" required autocomplete="off" placeholder="登录账号"></label><label>显示名称<input v-model="form.displayName" placeholder="用户姓名"></label><label>初始密码<input v-model="form.password" type="password" required minlength="6" autocomplete="new-password" placeholder="至少 6 位"></label><label>系统角色<select v-model="form.role"><option value="USER">普通用户</option><option value="ADMIN">管理员</option></select></label><button class="primary" :disabled="busy"><Check/>{{busy?'正在创建…':'创建用户'}}</button></form></div>
</main></template>

<style scoped>
.users-page{min-height:100vh;padding:36px clamp(24px,5vw,72px);background:radial-gradient(circle at 80% 0,#eee9ff,transparent 28%),#f8f7fb;color:#34303d}.users-page>header{max-width:1180px;margin:auto;display:grid;grid-template-columns:180px 1fr auto;align-items:center}.back{justify-self:start;border:0;background:transparent;color:#716a7b;display:flex;align-items:center;gap:7px}.back svg{width:18px}.users-page h1{margin:5px 0;font-size:34px}.users-page header p{margin:0;color:#898391}.users-card{max-width:1180px;margin:30px auto;background:#fff;border:1px solid #e9e5ee;border-radius:20px;box-shadow:0 20px 55px #49386f0c;overflow:hidden}.users-toolbar{padding:18px 22px;border-bottom:1px solid #eeeaf2;display:flex;align-items:center;justify-content:space-between;color:#928b99;font-size:12px}.search-box{width:320px;height:40px;border:1px solid #e3deea;border-radius:11px;display:flex;align-items:center;padding:0 12px}.search-box svg{width:15px}.search-box input{border:0;outline:0;width:100%;padding-left:9px}.table-head,.user-table article{display:grid;grid-template-columns:2fr 1fr 1fr 120px;align-items:center;gap:18px;padding:12px 22px}.table-head{font-size:10px;font-weight:700;letter-spacing:1px;color:#9b94a2;background:#faf9fc}.user-table article{min-height:72px;border-top:1px solid #f0edf3}.user-name{display:flex;align-items:center;gap:11px}.user-name>span{width:38px;height:38px;border-radius:11px;background:#eee9f7;color:#6d5bbb;display:grid;place-items:center;font-weight:700}.user-name label{display:flex;flex-direction:column}.user-name input{border:0;background:transparent;font-weight:700;color:#393440;outline:0}.user-name small{color:#99929f}.user-table select,.modal select{border:1px solid #e1dce7;background:#fff;border-radius:9px;padding:9px}.status-switch{border:0;background:#f2eff4;color:#8a838f;border-radius:10px;padding:8px 10px;display:flex;align-items:center;gap:7px}.status-switch i{width:7px;height:7px;border-radius:50%;background:#aaa}.status-switch.enabled{background:#eaf7f0;color:#438064}.status-switch.enabled i{background:#51a879}.row-actions{display:flex;gap:6px}.row-actions button{width:34px;height:34px;border:0;border-radius:9px;background:#f4f1f7;color:#746d7d;display:grid;place-items:center}.row-actions svg{width:15px}.row-actions .remove{color:#bc5365;background:#fff0f2}.no-users{padding:60px;text-align:center;color:#a29ba8}.no-users svg{display:block;margin:0 auto 10px}.modal select{width:100%}.modal .primary{margin-top:25px}@media(max-width:760px){.users-page>header{grid-template-columns:1fr;gap:18px}.users-page>header .primary{justify-self:start}.table-head{display:none}.user-table article{grid-template-columns:1fr 1fr}.users-toolbar{align-items:flex-start;gap:10px;flex-direction:column}.search-box{width:100%}}
</style>
